language: python
python:
  - "2.7"
  - "3.3"
env:
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
# command to install dependencies
install:
  - "pip install -q -e ."
  - "pip install -q -r demo/requirements.txt"
  - "pip install -q Django==$DJANGO_VERSION"

# command to run tests
script: "cd demo && python manage.py test plans"
